### ISSUE TITLE
Add parentheses for legato based on LilyPond slur syntax

### ISSUE THREAD

**Issue by pinobatch** [Qix-/pently#3]
"Legato" in Pently refers to an instantaneous change in the base pitch of a note without restarting the note's envelope. Currently in `pentlyas.py`, it's possible to trigger legato in a pitched pattern by adding `~` to the preceding note. This is derived from LilyPond [tie syntax][1]. But LilyPond also has [slur syntax][1], triggered with `(` suffix on the note before the first legato note and `)` suffix on the last legato note. For example, these should be equivalent, where only the C, F, and G get a new envelope:

    c4~ d~ e f g2
    c4( d e) f g2

  [1]: http://www.lilypond.org/doc/v2.16/Documentation/learning/ties-and-slurs

**Comment by Qix-** [comment]
Awesome 💃
